services:
  kumod:
    container_name: kumod
    image: ghcr.io/kumocorp/kumomta:latest
    volumes:
      - ./.docker/kumod:/opt/kumomta/etc
    restart: unless-stopped
    ports:
      - "25:2525"
    environment:
      - KUMO_LOG_LEVEL=debug

  fastapi:
    container_name: fastapi
    build:
      context: ./
      dockerfile: ./.docker/fastapi/Dockerfile
    volumes:
      - ./fastapi:/app
    ports:
      - "8080:8000"
    env_file:
      - ./.env

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - DEBUG=0
    volumes:
      - ./.docker/localstack/mount:/var/lib/localstack
      - ./localstack:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/localstack/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
      - ./.env:/app/.env
    env_file:
      - ./.env

  robin:
    container_name: robin
    build:
      context: ./
      dockerfile: ./.docker/robin/Dockerfile
    volumes:
      - ./robin:/usr/src/robin/cfg/
