services:
  kumod:
    container_name: kumod
    image: ghcr.io/kumocorp/kumomta:latest
    volumes:
      - ./.docker/kumod:/opt/kumomta/etc
    restart: unless-stopped
    ports:
      - "25:2525"
    environment:
      - KUMO_LOG_LEVEL=debug

  fastapi:
    container_name: fastapi
    build:
      context: ./
      dockerfile: ./.docker/fastapi/Dockerfile
    volumes:
      - ./fastapi:/app
    ports:
      - "8080:8000"

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
    volumes:
      - ./.docker/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.

  worker:
    container_name: worker
    build:
      context: ./
      dockerfile: ./.docker/worker/Dockerfile
    volumes:
      - ./worker:/app
